import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import AuthProvider from "../providers/auth-provider";
import { EdgeStoreProvider } from "@/lib/edgestore";

// Configure the Inter font
const interFont = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${interFont} antialiased`}>
          <EdgeStoreProvider>
            <div className="min-h-screen bg-gradient-to-tr from-zinc-50 to-zinc-100">
              <div className="wrapper">
                <Navbar />
                {children}
                <Footer />
              </div>
            </div>
          </EdgeStoreProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
